# Generated by Django 5.0.14 on 2025-07-06 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_thamso_diemdatmon'),
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thamso',
            name='ChoPhepSuaDiem',
            field=models.BooleanField(default=True, help_text='Cho phép giáo viên sửa điểm hay không'),
        ),
        migrations.AddField(
            model_name='thamso',
            name='GhiChu',
            field=models.TextField(blank=True, help_text='Ghi chú nội bộ', null=True),
        ),
        migrations.AddField(
            model_name='thamso',
            name='HocKy',
            field=models.ForeignKey(blank=True, help_text='Học kỳ áp dụng cho quy định này', null=True, on_delete=django.db.models.deletion.PROTECT, to='grading.hocky'),
        ),
        migrations.AddField(
            model_name='thamso',
            name='NgayCapNhat',
            field=models.DateTimeField(auto_now=True, help_text='Ngày giờ cập nhật gần nhất'),
        ),
        migrations.AddField(
            model_name='thamso',
            name='NguoiCapNhatCuoi',
            field=models.CharField(blank=True, help_text='Tên người cập nhật gần nhất', max_length=100, null=True),
        ),
    ]
