# Generated by Django 5.0.14 on 2025-07-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_thamso_chophepsuadiem_thamso_ghichu_thamso_hocky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thamso',
            name='ChoPhepSuaDiem',
        ),
        migrations.RemoveField(
            model_name='thamso',
            name='GhiChu',
        ),
        migrations.RemoveField(
            model_name='thamso',
            name='HocKy',
        ),
        migrations.RemoveField(
            model_name='thamso',
            name='NgayCapNhat',
        ),
        migrations.RemoveField(
            model_name='thamso',
            name='NguoiCapNhatCuoi',
        ),
        migrations.AddField(
            model_name='thamso',
            name='ChoPhepSuaDiemHK1',
            field=models.BooleanField(default=False, help_text='Cho phép giáo viên sửa điểm hay không'),
        ),
        migrations.AddField(
            model_name='thamso',
            name='ChoPhepSuaDiemHK2',
            field=models.BooleanField(default=False, help_text='Cho phép giáo viên sửa điểm hay không'),
        ),
    ]
