# Generated by Django 4.2 on 2025-07-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baocaomonhoc',
            name='IDHocKy',
        ),
        migrations.RemoveField(
            model_name='baocaomonhoc',
            name='IDLopHoc',
        ),
        migrations.RemoveField(
            model_name='baocaomonhoc',
            name='IDMonHoc',
        ),
        migrations.RemoveField(
            model_name='baocaomonhoc',
            name='IDNienKhoa',
        ),
        migrations.DeleteModel(
            name='BaoCaoHocKy',
        ),
        migrations.DeleteModel(
            name='BaoCaoMonHoc',
        ),
    ]
